obj-m += compat.o

compat-y += main.o

# Compat kernel compatibility code
compat-$(CONFIG_COMPAT_KERNEL_3_11) += compat-3.11.o
compat-$(CONFIG_COMPAT_KERNEL_3_12) += compat-3.12.o
compat-$(CONFIG_COMPAT_KERNEL_3_13) += compat-3.13.o
compat-$(CONFIG_COMPAT_KERNEL_3_15) += compat-3.15.o
compat-$(CONFIG_COMPAT_KERNEL_3_16) += compat-3.16.o
compat-$(CONFIG_COMPAT_KERNEL_3_18) += compat-3.18.o
compat-$(CONFIG_COMPAT_KERNEL_4_0) += compat-4.0.o
compat-$(CONFIG_COMPAT_KERNEL_4_1) += compat-4.1.o
